stages:
  - stage:
    displayName: Build
    jobs:
      - job: A
        pool:
          vmImage: windows-latest
        steps:
          - bash: echo 'Job A'
      - job: B
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: echo 'Job B'

  - stage: 
    displayName: Deploy
    jobs:
      - job: C
        pool:
         name: pool1
        steps:
          - bash: echo 'Job C'
